#IF any required configuration id not present in active profile it take properties from default application.property
#Llike i havent give DB configuration but it working bcz it takes from default property

Admin.userId=200
Admin.password=1


